#!/bin/bash

alias cz=chezmoi

alias vim=nvim

alias ssh='TERM=xterm-256color ssh'

alias ls='ls -F -h --color=always -v --author --time-style=long-iso'
alias la='ls -a'
alias ll='ls -l'
alias l='ls -l -a'

alias gs='git status'

alias dl='docker logs'
alias dc='docker compose'

alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.RunningFor}}\t{{.Ports}}"'
